yarnPath: .yarn/releases/yarn-4.6.0.cjs
nodeLinker: node-modules
npmScopes:
  bob-park:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAlwaysAuth: true
    npmAuthToken: ${GITHUB_NPM_AUTH_TOKEN}
