approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmScopes:
  bob-park:
    npmAlwaysAuth: true
    npmAuthToken: "${GITHUB_NPM_AUTH_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

yarnPath: .yarn/releases/yarn-4.17.0.cjs
